### ISSUE TITLE
Input point cloud filtering

### ISSUE THREAD

**Issue by dkanou** [team-vigir/vigir_terrain_classifier#2]
It appears that filltering brings back empty clouds.  In particular:

filterVoxelGridpcl::PointXYZ(point_cloud, 0.02, 0.02, 2.0);

1) looks weird: last value should be 0.2 instead of 2.0
2) the returned cloud is of 0 size (point_cloud_filter.h )

**Comment by astumpf** [comment]
1) It's intended. The 2.0 means that all values along the z-axis will be summed into one single voxel to prevent ambiguity along z-axis given x and y. We are currently working on better world model representation to allow multiple z-layers.
2) I don't have this issue with the provided test point clouds.
