### ISSUE TITLE
Recent commit broke compatability on pcl-1.7

### ISSUE THREAD

**Issue by allspawj** [team-vigir/vigir_terrain_classifier#3]
Your recent commit breaks comparability with PCL-1.7, the default version for ros indigo / ubuntu 14.04.

In case anyone else on 14.04 has had a problem compiling, just go back one revision and it should work fine.

**Comment by astumpf** [comment]
Thanks for comment. For convenience, I've added a indigo-devel branch removing the latest commit: https://github.com/team-vigir/vigir_terrain_classifier/tree/indigo-devel
